from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

EMERALD = colors.HexColor("#059669")
EMERALD_LIGHT = colors.HexColor("#ecfdf5")
EMERALD_BORDER = colors.HexColor("#a7f3d0")

AMBER = colors.HexColor("#d97706")
ROSE = colors.HexColor("#e11d48")
ROSE_LIGHT = colors.HexColor("#fff1f2")
ROSE_BORDER = colors.HexColor("#fecdd3")

SLATE_900 = colors.HexColor("#0f172a")
SLATE_700 = colors.HexColor("#334155")
SLATE_500 = colors.HexColor("#64748b")
SLATE_200 = colors.HexColor("#e2e8f0")
SLATE_100 = colors.HexColor("#f1f5f9")

PAGE_WIDTH, PAGE_HEIGHT = letter
CONTENT_WIDTH = PAGE_WIDTH - 1.4 * inch
HEADER_HEIGHT = 1.15 * inch


def _score_tier(score):
    if score >= 75:
        return EMERALD, "Strong Match"
    if score >= 50:
        return AMBER, "Moderate Match"
    return ROSE, "Needs Improvement"


def _draw_header_footer(canvas, doc, resume_name):
    canvas.saveState()

    # Header band
    canvas.setFillColor(SLATE_900)
    canvas.rect(0, PAGE_HEIGHT - HEADER_HEIGHT, PAGE_WIDTH, HEADER_HEIGHT, stroke=0, fill=1)

    canvas.setFillColor(EMERALD)
    canvas.rect(0, PAGE_HEIGHT - HEADER_HEIGHT - 3, PAGE_WIDTH, 3, stroke=0, fill=1)

    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 20)
    canvas.drawString(0.7 * inch, PAGE_HEIGHT - 0.55 * inch, "AI Resume Analyzer")

    canvas.setFillColor(colors.HexColor("#6ee7b7"))
    canvas.setFont("Helvetica", 11)
    canvas.drawString(0.7 * inch, PAGE_HEIGHT - 0.78 * inch, "Resume Match Analysis Report")

    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#94a3b8"))
    canvas.drawRightString(PAGE_WIDTH - 0.7 * inch, PAGE_HEIGHT - 0.55 * inch, resume_name[:48])

    # Footer
    canvas.setStrokeColor(SLATE_200)
    canvas.setLineWidth(0.75)
    canvas.line(0.7 * inch, 0.6 * inch, PAGE_WIDTH - 0.7 * inch, 0.6 * inch)

    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(SLATE_500)
    canvas.drawString(0.7 * inch, 0.42 * inch, "Generated by AI Resume Analyzer")
    canvas.drawRightString(PAGE_WIDTH - 0.7 * inch, 0.42 * inch, f"Page {doc.page}")

    canvas.restoreState()


def _info_table(analysis):
    rows = [
        ["Resume", analysis.resume.resume_file.name],
        ["Job Title", analysis.job.title],
        ["Analyzed On", analysis.created_at.strftime("%d %b %Y, %H:%M")],
    ]
    table = Table(rows, colWidths=[1.3 * inch, CONTENT_WIDTH - 1.3 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), SLATE_100),
        ("BOX", (0, 0), (-1, -1), 0.75, SLATE_200),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, SLATE_200),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("TEXTCOLOR", (0, 0), (0, -1), SLATE_700),
        ("TEXTCOLOR", (1, 0), (1, -1), SLATE_900),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
    ]))
    return table


def _score_section(score, styles):
    color, tier_label = _score_tier(score)
    clamped = max(0.0, min(100.0, score))

    heading = Paragraph("ATS MATCH SCORE", styles["SectionLabel"])

    big_number = Paragraph(
        f'<font color="{color.hexval()}"><b>{score:.0f}%</b></font>',
        ParagraphStyle("BigScore", fontSize=46, leading=52, alignment=1, fontName="Helvetica-Bold"),
    )

    tier = Paragraph(
        f'<font color="{color.hexval()}"><b>{tier_label}</b></font>',
        ParagraphStyle("Tier", fontSize=12, leading=16, alignment=1),
    )

    bar_total = CONTENT_WIDTH - 20
    filled = max(2, bar_total * (clamped / 100.0))
    remaining = max(0.01, bar_total - filled)

    bar = Table([["", ""]], colWidths=[filled, remaining], rowHeights=[10])
    bar.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, 0), color),
        ("BACKGROUND", (1, 0), (1, 0), SLATE_200),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))

    wrapper = Table(
        [[heading], [big_number], [tier], [Spacer(1, 6)], [bar]],
        colWidths=[CONTENT_WIDTH],
    )
    wrapper.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.75, SLATE_200),
        ("BACKGROUND", (0, 0), (-1, -1), colors.white),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, 0), 14),
        ("BOTTOMPADDING", (0, 2), (-1, 2), 14),
        ("LEFTPADDING", (0, 4), (-1, 4), 10),
        ("RIGHTPADDING", (0, 4), (-1, 4), 10),
    ]))
    return wrapper


def _skills_box(title, skills, styles, accent, bg, border, empty_text):
    heading = Paragraph(title, styles["SectionLabel"])

    if skills:
        bullet = f'<font color="{accent.hexval()}">&#9679;</font>'
        body_text = "&nbsp;&nbsp;&nbsp;".join(f"{bullet} {skill}" for skill in skills)
        body = Paragraph(body_text, ParagraphStyle(
            "SkillsBody", fontSize=9.5, leading=18, textColor=SLATE_900,
        ))
        box_bg, box_border = bg, border
    else:
        body = Paragraph(empty_text, ParagraphStyle(
            "SkillsEmpty", fontSize=9.5, leading=14, textColor=SLATE_500, fontName="Helvetica-Oblique",
        ))
        # Neutral styling when there's nothing to report -- an empty
        # "missing skills" box is good news, it shouldn't still look rose.
        box_bg, box_border = SLATE_100, SLATE_200

    box = Table([[body]], colWidths=[CONTENT_WIDTH])
    box.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.75, box_border),
        ("BACKGROUND", (0, 0), (-1, -1), box_bg),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
    ]))

    return [heading, Spacer(1, 6), box]


def _recommendation_box(recommendation, styles):
    heading = Paragraph("RECOMMENDATION", styles["SectionLabel"])

    body = Paragraph(recommendation, ParagraphStyle(
        "Recommendation", fontSize=10, leading=15, textColor=SLATE_700,
    ))

    box = Table([[body]], colWidths=[CONTENT_WIDTH - 4])
    box.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), SLATE_100),
        ("LINEBEFORE", (0, 0), (0, -1), 3, EMERALD),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ("TOPPADDING", (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
    ]))

    return [heading, Spacer(1, 6), box]


def build_analysis_report(response, analysis, matched, missing, recommendation):
    styles = {
        "SectionLabel": ParagraphStyle(
            "SectionLabel", fontSize=10, leading=13, fontName="Helvetica-Bold",
            textColor=SLATE_700, spaceAfter=0, characterSpacing=0.5,
        ),
    }

    doc = SimpleDocTemplate(
        response,
        pagesize=letter,
        topMargin=HEADER_HEIGHT + 0.35 * inch,
        bottomMargin=0.9 * inch,
        leftMargin=0.7 * inch,
        rightMargin=0.7 * inch,
        title="AI Resume Analyzer Report",
    )

    story = []

    story.append(Paragraph("SUMMARY", styles["SectionLabel"]))
    story.append(Spacer(1, 6))
    story.append(_info_table(analysis))
    story.append(Spacer(1, 18))

    story.append(_score_section(analysis.similarity_score, styles))
    story.append(Spacer(1, 20))

    story.extend(_skills_box(
        "MATCHED SKILLS", matched, styles,
        accent=EMERALD, bg=EMERALD_LIGHT, border=EMERALD_BORDER,
        empty_text="No matched skills found.",
    ))
    story.append(Spacer(1, 16))

    story.extend(_skills_box(
        "MISSING SKILLS", missing, styles,
        accent=ROSE, bg=ROSE_LIGHT, border=ROSE_BORDER,
        empty_text="No missing skills.",
    ))
    story.append(Spacer(1, 16))

    story.extend(_recommendation_box(recommendation, styles))

    resume_name = analysis.resume.resume_file.name

    def on_page(canvas, doc_):
        _draw_header_footer(canvas, doc_, resume_name)

    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
