# Generated by Django 6.0.7 on 2026-07-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_jobdescription_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='matched_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='missing_skills',
            field=models.TextField(blank=True),
        ),
    ]
